### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by mingchuan123** [torrvision/siamfc-tf#17]
Hi there, I just got an error below when trying to run the code on the mac. Can you give some hints? Thanks.

```
Using Tensorflow 1.1.0
Traceback (most recent call last):
  File "run_tracker_evaluation.py", line 174, in <module>
    sys.exit(main())
  File "run_tracker_evaluation.py", line 16, in main
    hp, evaluation, run, env, design = parse_arguments()
  File "/Users/zhaomingchuan/siamfc-tf/src/parse_arguments.py", line 10, in parse_arguments
    evaluation = json.load(json_file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by jvlmdr** [comment]
Please post your `parameters/evaluation.json` file?
