### ISSUE TITLE
something wrong with /usr/lib/python2.7/json/decoder.py

### ISSUE THREAD

**Issue by jsjs0827** [torrvision/siamfc-tf#35]
Using Tensorflow 1.1.0
Traceback (most recent call last):
  File "/data/siamfc-tf/siamfc-tf-master/run_tracker_evaluation.py", line 174, in <module>
    sys.exit(main())
  File "/data/siamfc-tf/siamfc-tf-master/run_tracker_evaluation.py", line 16, in main
    hp, evaluation, run, env, design = parse_arguments()
  File "/data/siamfc-tf/siamfc-tf-master/src/parse_arguments.py", line 10, in parse_arguments
    evaluation = json.load(json_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 8 column 1 (char 188)
what should I do?

**Comment by jvlmdr** [comment]
Can you please post the relevant json file?
