### ISSUE TITLE
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by deimsdeutsch** [torrvision/siamfc-tf#41]
/opt/github2/siamfc-tf# python3 run_tracker_evaluation.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

**Comment by jvlmdr** [comment]
This is probably due to a mis-match between your TF and CUDA versions.

If you are installing TF from PyPI (i.e. using `pip install`), then see this stackoverflow answer:
https://stackoverflow.com/a/50622526/1136018
