### ISSUE TITLE
Error when Settings things up with virtualenv

### ISSUE THREAD

**Issue by Jumabek** [torrvision/siamfc-tf#6]
Hi @bertinetto, @jvlmdr  ,
Could you help me out please?

I am getting following error in windows 10

`Command "python setup.py egg_info" failed with error code 1 in c:\users\jumab\appdata\local\temp\pip-build-etluxy\matplotlib\
`
when I run 
`pip install -r requirements.txt `in cmd (on administrator mode) in step 6

This is complete error message:
```
  Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\jumab\appdata\local\temp\pip-build-etluxy\matplotlib\setup.py", line 268, in <module>
        **extra_args
      File "c:\anaconda2\Lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "e:\code\ve-tracking\lib\site-packages\setuptools\dist.py", line 320, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "e:\code\ve-tracking\lib\site-packages\setuptools\dist.py", line 377, in fetch_build_eggs
        replace_conflicting=True,
      File "e:\code\ve-tracking\lib\site-packages\pkg_resources\__init__.py", line 852, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "e:\code\ve-tracking\lib\site-packages\pkg_resources\__init__.py", line 1124, in best_match
        return self.obtain(req, installer)
      File "e:\code\ve-tracking\lib\site-packages\pkg_resources\__init__.py", line 1136, in obtain
        return installer(requirement)
      File "e:\code\ve-tracking\lib\site-packages\setuptools\dist.py", line 445, in fetch_build_egg
        return cmd.easy_install(req)
      File "e:\code\ve-tracking\lib\site-packages\setuptools\command\easy_install.py", line 673, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "e:\code\ve-tracking\lib\site-packages\setuptools\command\easy_install.py", line 699, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "e:\code\ve-tracking\lib\site-packages\setuptools\command\easy_install.py", line 880, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "e:\code\ve-tracking\lib\site-packages\setuptools\command\easy_install.py", line 1119, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "e:\code\ve-tracking\lib\site-packages\setuptools\command\easy_install.py", line 1107, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
```

Thx

**Comment by bertinetto** [comment]
Hi Jumabek,
Sorry but we are not able to test on windows at the moment.

It seems that the last line of the error message is telling though:
`Setup script exited with error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27`

Please feel free to post here the solution of further problem, someone else using Windows might be able to help.

**Comment by mingchuan123** [comment]
Hi @bertinetto, @jvlmdr:
I am trying to run the code on mac, all the requirements have been successfully installed. Pretrained model and data have been downloaded but it feeds back some errors below, can you give some hints? Thanks.
```
Traceback (most recent call last):
  File "run_tracker_evaluation.py", line 6, in <module>
    import src.siamese as siam
  File "/Users/zhaomingchuan/siamfc-tf/src/siamese.py", line 1, in <module>
    import tensorflow as tf
  File "/Users/zhaomingchuan/ve-tracking/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/zhaomingchuan/ve-tracking/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/zhaomingchuan/ve-tracking/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/zhaomingchuan/ve-tracking/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/zhaomingchuan/ve-tracking/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/zhaomingchuan/ve-tracking/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: dlopen(/Users/zhaomingchuan/ve-tracking/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Users/zhaomingchuan/ve-tracking/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

**Comment by jvlmdr** [comment]
Hi! Are you able to run the following in python?
```import tensorflow as tf
tf.Session()```
Do you have CUDA 8 installed?

**Comment by jvlmdr** [comment]
Hi!
Please don't start a new topic in a closed issue. Open a new issue.
Are you able to run the following in python?
```python
import tensorflow as tf
tf.Session()
```
What is your OS? Do you have CUDA 8 installed?

**Comment by mingchuan123** [comment]
Hi Valmadre, thanks for reply. I just install a CPU version instead of GPU,
I guess install tensorflow gpu needs some dependencies on mac. But  there
is another issue below:


Traceback (most recent call last):

  File "run_tracker_evaluation.py", line 174, in <module>

    sys.exit(main())

  File "run_tracker_evaluation.py", line 38, in main

    gt, frame_name_list, frame_sz, n_frames = _init_video(env, evaluation,
videos_list[i])

  File "run_tracker_evaluation.py", line 119, in _init_video

    frame_name_list = [f for f in os.listdir(video_folder) if
f.endswith(".jpg")]

OSError: [Errno 20] Not a directory: 'data/validation/README.txt'


I have put the validation folder to the data folder and the image folder is
selected as vot2016_ball1.

2017-10-26 17:17 GMT-04:00 Jack Valmadre <notifications@github.com>:

**Comment by jvlmdr** [comment]
I'm glad you resolved the CUDA issue. Please open a new issue for this.
